from parserfa import *

def cminusParseFA(apply_fa):
    #TODO: build fa based on rules, firsts, and follows, return nonterminal "Program"
    # TERMINALS
    ID = Terminal(Token.ID, False)
    NUM = Terminal(Token.NUM, False)
    EOF = Terminal(Token.EOF, False)

    SEMICOLON = Terminal(";")
    COLON = Terminal(":")
    COMMA = Terminal(",")
    OPENBRACKET = Terminal("[")
    CLOSEBRACKET = Terminal("]")
    OPENPAR = Terminal("(")
    CLOSEPAR = Terminal(")")
    OPENCURLY = Terminal("{")
    CLOSECURLY = Terminal("}")
    LESS = Terminal("<")
    DOUBLEEQUAL = Terminal("==")
    PLUS = Terminal("+")
    MINUS = Terminal("-")
    MULT = Terminal("*")
    EQUAL = Terminal("=")
    IF = Terminal("if")
    ELSE = Terminal("else")
    VOID = Terminal("void")
    INT = Terminal("int")
    WHILE = Terminal("while")
    BREAK = Terminal("break")
    RETURN = Terminal("return")

    # NONTERMINALS
    program = NonTerminal([INT, VOID, EOF], apply_fa, "Program")
    declaration_list = NonTerminal([INT, VOID, ID, SEMICOLON, NUM, OPENPAR, OPENCURLY, CLOSECURLY, BREAK, IF, WHILE, RETURN, PLUS, MINUS, EOF], apply_fa, "DeclarationList")
    declaration = NonTerminal([INT, VOID], apply_fa, "Declaration")
    declaration_initial = NonTerminal([INT, VOID], apply_fa, "Declaration Initial")
    declaration_prime = NonTerminal([SEMICOLON, OPENBRACKET, OPENPAR], apply_fa, "DeclarationPrime")
    var_declaration_prime = NonTerminal([SEMICOLON, OPENBRACKET], apply_fa, "VarDeclarationPrime")
    fun_declaration_prime = NonTerminal([OPENPAR], apply_fa, "FunDeclarationPrime")
    type_specifier = NonTerminal([INT, VOID], apply_fa, "TypeSpecifier")
    params = NonTerminal([INT, VOID], apply_fa, "Params")
    param_list = NonTerminal([COMMA,CLOSEPAR], apply_fa, "ParamList")
    param = NonTerminal([INT, VOID],apply_fa, "Param")
    param_prime = NonTerminal([OPENBRACKET, CLOSEPAR, COMMA], apply_fa, "ParamPrime")
    compound_stmt = NonTerminal([OPENCURLY], apply_fa, "CompoundStmt")
    statement_list = NonTerminal([ID, SEMICOLON, NUM, OPENPAR, OPENCURLY, BREAK, IF, WHILE, RETURN, PLUS, MINUS, CLOSECURLY], apply_fa, "StatementList")
    statement = NonTerminal([ID, SEMICOLON, NUM, OPENPAR, OPENCURLY, BREAK, IF, WHILE, RETURN, PLUS, MINUS], apply_fa, "Statement")
    expression_stmt = NonTerminal([ID, SEMICOLON, NUM, OPENPAR, BREAK, PLUS, MINUS], apply_fa, "ExpressionStmt")
    selection_stmt = NonTerminal([IF], apply_fa, "SelectionStmt")
    iteration_stmt = NonTerminal([WHILE], apply_fa, "IterationStmt")
    return_stmt = NonTerminal([RETURN], apply_fa, "ReturnStmt")
    return_stmt_prime = NonTerminal([ID, SEMICOLON, NUM, OPENPAR, PLUS, MINUS], apply_fa, "ReturnStmtPrime")
    expression = NonTerminal([ID, NUM, OPENPAR, PLUS, MINUS], apply_fa, "Expression")
    b = NonTerminal([OPENBRACKET, OPENPAR, EQUAL, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA], apply_fa, "B")
    h = NonTerminal([EQUAL, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA], apply_fa, "H")
    simple_expression_zegond = NonTerminal([NUM, OPENPAR, PLUS, MINUS], apply_fa, "SimpleExpressionZegond")
    simple_expression_prime = NonTerminal([OPENPAR, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA], apply_fa, "SimpleExpressionPrime")
    c = NonTerminal([LESS, DOUBLEEQUAL, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA], apply_fa, "C")
    relop = NonTerminal([LESS, DOUBLEEQUAL], apply_fa, "Relop")
    additive_expression = NonTerminal([ID, NUM, OPENPAR, PLUS, MINUS], apply_fa, "AdditiveExpression")
    additive_expression_prime = NonTerminal([OPENPAR, PLUS, MINUS, MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL], apply_fa, "AdditiveExpressionPrime")
    additive_expression_zegond = NonTerminal([NUM, OPENPAR, PLUS, MINUS], apply_fa, "AdditiveExpressionZegond")
    d = NonTerminal([PLUS, MINUS, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL], apply_fa, "D")
    addop = NonTerminal([PLUS, MINUS], apply_fa, "Addop")
    term = NonTerminal([ID, NUM, OPENPAR, PLUS, MINUS], apply_fa, "Term")
    term_prime = NonTerminal([OPENPAR, MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS], apply_fa, "TermPrime")
    term_zegond = NonTerminal([NUM, OPENPAR, PLUS, MINUS], apply_fa, "TermZegond")
    g = NonTerminal([MULT, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS], apply_fa, "G")
    signed_factor = NonTerminal([ID,NUM, OPENPAR, PLUS, MINUS], apply_fa, "SignedFactor")
    signed_factor_prime = NonTerminal([OPENPAR, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT], apply_fa, "SignedFactorPrime")
    signed_factor_zegond = NonTerminal([NUM, OPENPAR, PLUS, MINUS], apply_fa, "SignedFactorZegond")
    factor = NonTerminal([ID, NUM, OPENPAR], apply_fa, "Factor")
    var_call_prime = NonTerminal([OPENBRACKET, OPENPAR, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT], apply_fa, "VarCallPrime")
    var_prime = NonTerminal([OPENBRACKET, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT], apply_fa, "VarPrime")
    factor_prime = NonTerminal([OPENPAR, SEMICOLON, CLOSEBRACKET, CLOSEPAR, COMMA, LESS, DOUBLEEQUAL, PLUS, MINUS, MULT], apply_fa, "FactorPrime")
    factor_zegond = NonTerminal([NUM, OPENPAR], apply_fa, "FactorZegond")
    args = NonTerminal([ID, NUM, OPENPAR, PLUS, MINUS, CLOSEPAR], apply_fa, "Args")
    arg_list = NonTerminal([ID, NUM,OPENPAR, PLUS, MINUS], apply_fa, "ArgList")
    arg_list_prime = NonTerminal([COMMA, CLOSEPAR], apply_fa, "ArgListPrime")

    # 1. PROGRAM
    program_s0 = State()
    programfa = ParserFA(program_s0)
    program_s1 = State((StateType.ACCEPT,))
    programfa.addState(program_s1)
    programfa.addTransition(program_s0, program_s1, declaration_list)
    program.set_fa(programfa)

    # 2. DECLARATION LIST
    declaration_list_s0 = State()
    declaration_list_fa = ParserFA(declaration_list_s0)
    declaration_list_s1 = State()
    declaration_list_s2 = State((StateType.ACCEPT,))
    declaration_list_fa.addState(declaration_list_s1)
    declaration_list_fa.addState(declaration_list_s2)
    declaration_list_fa.addTransition(declaration_list_s0, declaration_list_s1, declaration)
    declaration_list_fa.addTransition(declaration_list_s1, declaration_list_s2, declaration_list)
    declaration_list_fa.addTransition(declaration_list_s0, declaration_list_s2, None)
    declaration_list.set_fa(declaration_list_fa)

    # 3. DECLARATION
    declaration_s0 = State()
    declaration_fa = ParserFA(declaration_s0)
    declaration_s1 = State()
    declaration_s2 = State((StateType.ACCEPT, ))
    declaration_fa.addState(declaration_s1)
    declaration_fa.addState(declaration_s2)
    declaration_fa.addTransition(declaration_s0, declaration_s1, declaration_initial)
    declaration_fa.addTransition(declaration_s1, declaration_s2, declaration_prime)
    declaration.set_fa(declaration_fa)

    # 4. DECLARATION INITIAL
    declaration_initial_s0 = State()
    declaration_initial_fa = ParserFA(declaration_initial_s0)
    declaration_initial_s1 = State()
    declaration_initial_s2 = State((StateType.ACCEPT, ))
    declaration_initial_fa.addState(declaration_initial_s1)
    declaration_initial_fa.addState(declaration_initial_s2)
    declaration_initial_fa.addTransition(declaration_initial_s0, declaration_initial_s1, type_specifier)
    declaration_initial_fa.addTransition(declaration_initial_s1, declaration_initial_s2, ID)
    declaration_initial.set_fa(declaration_initial_fa)

    # 5. DECLARATION PRIME

    return program